version: '2'
services:
  # The first container will do the scrubbing (checks that the checksums match). See shatag-documentation for more information.
  # With the default options, the log will only display alerts about corrupted files.
  shatag:
    image: kalaksi/shatag
    restart: 'no'
    cap_drop:
      - ALL
    volumes:
      - /mnt/yourdata_one:/data/one
      - /mnt/yourdata_two:/data/two
    # Example of changing the user
    # user: '2000:2000'

  # The second container will monitor the files and update the checksums if files are modified or created.
  # The log will display the filenames that have changed.
  shatagd:
    image: kalaksi/shatag
    restart: unless-stopped
    cap_drop:
      - ALL
    volumes_from:
      - shatag
    environment:
      SHATAG_RUN_DAEMON: 1
